image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: open-docker-compose # runs during prebuild
    command: docker-compose up -d
  - name: run-mongodb
    init: mkdir -p /workspace/data && mongod --dbpath /workspace/data && 
          mysql -e "CREATE DATABASE order_service;" && mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root_password';"


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
