image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: run-mongodb
    init: mysql -e "CREATE DATABASE order_service;" && mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root_password';"
        # mkdir -p /workspace/data && mongod --dbpath /workspace/data &&
    command: docker run -p 8282:8282 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:18.0.0 start-dev


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
