version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 8088 :8088
    volumes:
      - /workspace/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      

#version: '3.7'
#services:
  #mongodb_container:
  #  image: mongo:latest
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: rootpassword
  #  ports:
  #    - 27017:27017
  #  volumes:
  #    - /workspace/mongo:/data/db

  keycloak:
      container_name: keycloak
      image: ${IMAGE}
      environment:
        DB_VENDOR: h2
        PROXY_ADDRESS_FORWARDING: "true"
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        KEYCLOAK_STATISTICS: ${KEYCLOAK_STATISTICS}
        KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL}
        JAVA_OPTS_APPEND: "${JAVA_OPTS_APPEND}"
      ports:
        - 8181 :8080

volumes:
  mongo: