version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:S3cret
      - MONGO_INITDB_DATABASE:testdb
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=mysql_user
      - MYSQL_DATABASE=order_db

  #keycloak:
  #    container_name: keycloak
  #    image: ${IMAGE}
  #    environment:
  #      DB_VENDOR: h2
  #      PROXY_ADDRESS_FORWARDING: "true"
  #      KEYCLOAK_USER: ${KEYCLOAK_USER}
  #      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  #      KEYCLOAK_STATISTICS: ${KEYCLOAK_STATISTICS}
  #      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL}
  #     JAVA_OPTS_APPEND: "${JAVA_OPTS_APPEND}"
  #    ports:
  #      - 8181:8080

  postgres:
      image: postgres
      volumes:
        - ~/workspace/postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:17.0.1
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
      ports:
        - 8181:8080
      depends_on:
        - postgres

volumes:
  postgres_data:
    driver: local
#volumes:
#  mongo:
 
