version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:S3cret
      - MONGO_INITDB_DATABASE:testdb
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=mysql_user
      - MYSQL_DATABASE=order_db

  #keycloak:
  #    container_name: keycloak
  #    image: ${IMAGE}
  #    environment:
  #      DB_VENDOR: h2
  #      PROXY_ADDRESS_FORWARDING: "true"
  #      KEYCLOAK_USER: ${KEYCLOAK_USER}
  #      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  #      KEYCLOAK_STATISTICS: ${KEYCLOAK_STATISTICS}
  #      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL}
  #     JAVA_OPTS_APPEND: "${JAVA_OPTS_APPEND}"
  #    ports:
  #      - 8181:8080

  postgres:
    image: postgres
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_STATISTICS: ${KEYCLOAK_STATISTICS}
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL}
      JAVA_OPTS_APPEND: "${JAVA_OPTS_APPEND}"
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
    ports:
      - 8181:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
#volumes:
#  mongo:
 
