server:
    port: 8081
    
spring:
  application:
    name: product-service

  data:
      mongodb:
        uri: mongodb://localhost:27017/product_service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka