server:
    port: 0
    
spring:
  application:
    name: product-service

  zipkin:
    base-url: http://localhost:9411
    
  sleuth:
        sampler:
            probability: 1.0

  data:
      mongodb:
        host:mongodb
        port:27017
        username:root
        password:S3cret
        database:product_service
        authentication-database:testdb
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka