server:
    port: 0

spring:
    application:
        name: product-service

    data:
        mongodb:
            host: mongodb
            port: 27017
            username: root
            password: S3cret
            database: product_service
            authentication-database: testdb
management:
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
    tracing:
        sampling:
            probability: 1.0
    # Actuator Prometheus Endpoint
    endpoints:
        web:
            exposure:
                include: prometheus
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka
