server:
    port: 0
    
spring:
  application:
    name: product-service

  data:
      mongodb:
        host:localhost
        port:27017
        username:root
        password:S3cret
        database:product_service
        authentication-database:testdb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka