server:
  port: 8761

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false

  username: eureka # ${EUREKA_USERNAME:eureka}

  password: password #${EUREKA_PASSWORD:password}