#
eureka:
  instance:
    hostname: localhost
    # preferIpAddress: true

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


app:
  eureka:
    username: eureka
    
    password: password

server:
  port: 8761

#${EUREKA_USERNAME:eureka}
#${EUREKA_PASSWORD:password}

#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#server.port=8761
#app.eureka.username=eureka
#app.eureka.password=password