
server:
    port: 0

spring:
    application:
      name: inventory-service

    zipkin:
        base-url: http://localhost:9411
    
    sleuth:
        sampler:
            probability: 1.0

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/inventory_service
        username: root
        password: S3cret
    jpa:
        hibernate.ddl-auto: create-drop
        generate-ddl: true
        show-sql: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka
