server:
  port: 8761

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false


app:
  username:${EUREKA_USERNAME:eureka}

  password:${EUREKA_PASSWORD:password}