server:
  port: 8761
#
eureka:
  instance:
    #hostname: localhost
    preferIpAddress: true

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/


app:
  eureka:
    username: ${EUREKA_USERNAME:eureka}
    password: ${EUREKA_PASSWORD:password}

#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#server.port=8761
#app.eureka.username=eureka
#app.eureka.password=password